#!/bin/sh

set -o errexit

mkdir -p ebin logs blocks wallet_lists txs blocks/enc priv data/genesis_txs

if [ -t 1 ]; then
	SHELL_OPTS=
else
	SHELL_OPTS=-noinput
fi

ERL_OPTS="$ERL_OPTS -pa ebin/"
ERL_OPTS="$ERL_OPTS -pa lib/jiffy/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/cowboy/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/cowlib/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/ranch/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/prometheus/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/accept/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/prometheus_process_collector/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/prometheus_httpd/ebin"
ERL_OPTS="$ERL_OPTS -pa lib/prometheus_cowboy/ebin"
ERL_OPTS="$ERL_OPTS -sasl errlog_type error"
ERL_OPTS="$ERL_OPTS -s prometheus"

exec erl $SHELL_OPTS $ERL_OPTS -s ar rebuild -run ar main "$@"
